[versions]
revanced-patcher = "21.0.0"
# Tracking https://github.com/google/smali/issues/64.
#noinspection GradleDependency
smali = "3.0.5"
annotation = "1.9.1"

[libraries]
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }