[versions]
revanced-patcher = "21.0.0"
# Tracking https://github.com/google/smali/issues/64.
#noinspection GradleDependency
smali = "3.0.5"
annotation = "1.9.1"
agp = "8.2.2"

[libraries]
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }

[libraries]
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }

